### ISSUE TITLE
Create Documentation for App

### ISSUE THREAD

**Issue by LaggyHammer** [LaggyHammer/optical_char_recog#30]
- [x] Detailed Readme with GUI screenshots (configurator & main app)
- [ ] Walkthrough video (optional)
- [ ] Convert manual to markdown

**Comment by amithtm** [comment]
[Work In Progreess](https://cloudweir-my.sharepoint.com/:w:/g/personal/amith_tm_mail_weir/EarZnhreMJJNoa1Bgd2oTtcBcKCEiW3QuwhmO-r0iSBKTw?e=Tc8XlS)
